name = "Create Sublime - Fabric 1.20.1"
author = "caseykat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1742404a3da3de366e3fcb51ecbb9467531d4fd390a1e9638fda1fbf3b54c10"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
