name = "Create Sublime - Fabric 1.20.1"
author = "caseykat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af9ba206ae50348b12c42f26678a03389d35764b52421a32b7b948c4752c056f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
