enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 360
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 11.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 3
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
cinderscapes = true
naturalist = true
everycomp = true
spelunkery = true
farmersdelight = true
nox = true
cccbridge = true
createbigcannons = true
infinitybuttons = true
alloy_forgery = true
suppsquared = true
terrestria = true
endrem = true
create = true
mythicmounts = true
potioncauldron = true
echochest = true
copper_golem = true
davespotioneering = true
twigs = true
sculk_redstone_components = true
minecraft = true
attraction = true
lootr = true
chalk = true
blossom = true
snifferplus = true
origins = true
createaddition = true
sleep_tight = true
railways = true
milk = true
numismatic-overhaul = true
traverse = true
snowrealmagic = true
computercraft = true
mythicmetals = true
supplementaries = true
betterlily = true
treechop = true
netherchested = true
delightfulcreators = true
grapplemod = true
